### ISSUE TITLE
Change the link in contact us

### ISSUE THREAD

**Issue by omrivardi** [omrivardi/menakim#103]
Need to change the link to https://forms.gle/xDpcZQMBruBry9Kr7

![image](https://user-images.githubusercontent.com/21314351/109551336-1b555080-7ad9-11eb-9579-dba12dc935e1.png)

**Comment by mtwn105** [comment]
Hi @omrivardi I would like to work one this. Can you tell me which component is this as I don't understand this language.

**Comment by omrivardi** [comment]
Hi @mtwn105, The issue was closed but we can open specific issues with description if you'd like.
