### ISSUE TITLE
Register screen text size modification

### ISSUE THREAD

**Issue by DanLiebeschutz** [omrivardi/menakim#90]
![image](https://user-images.githubusercontent.com/61632147/108606619-b0fb2c80-73c3-11eb-907b-39f1775de4f2.png)

הפונטים כאן בגדלים שונים.  אפשר שהחלק של הסחטיין עד השימ/י לב יהיה דווקא בגודל של החלק של השימי לב והחלק של השימי לב יהיה בגודל של הסחטיין?

בנוסף, אפשר להוריד את ה״שימ/י לב:״
ולהצמיד את הקישור לערכה לבלוק הטקסט שמעליו

**Comment by omrivardi** [comment]
אפשר לסגור? @DanLiebeschutz

**Comment by DanLiebeschutz** [comment]
> אפשר לסגור? @DanLiebeschutz 

כן
